name: CI
on:
  pull_request:
    branches:
      - main
      - feature
jobs:
  check:
    name: Check stuff
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build Slides
        run: yarn build
